### ISSUE TITLE
任意の単語について関連する単語を出力する方法

### ISSUE THREAD

**Issue by fummicc1** [fummicc1/Mom#1]
# 注意点
- 上のとうりの質問ですけど、下のようなものは無しにしたい。
ex: アイデア✖️共有->考え、共有　（そのまま訳してしまう）
ex: アイデア✖️共有->アイデアマン　（元の単語に付け足して似た意味の別の単語にする）

# 実現したいこと
- 関連する単語を少なくとも8個くらいは出力したい
ex: アイデア✖️共有-> 会議、クリエイティブ、らせん構造、体細胞分裂、ワクワク、個性、影、黄色
- 精度は別にこだわってなくて、個数をいっぱい出力したい
- デベロッパーがそれぞれの投稿に対して、毎回入力するとかでも可能ならばOK

**Comment by fummicc1** [comment]
正直、関連語というよりは連想語に近いので、ユーザーの気持ちとぴったり一致しなくても良いです。
あと、可能性少しでもあるなら教えてください。なんでもします笑

**Comment by ka0ru19** [comment]
ユーザーはそれぞれの投稿に対して、タグをつけて投稿して、
デベロッパーは、入力するときにワードとは別で、タグも指定すればいいんじゃないかな。
そんでデベが入力したワードとタグから、ユーザが投稿したデータベースから探索しつつ、
数をもっと出したいんだったら、タグにANYタグとか用意しておいて、デベロッパーのどんな投稿に対してもANYの中からランダムでいくつか出力するようにするのはどうだろう、、！

**Comment by ka0ru19** [comment]
タグには、ジャンルっぽいことを指定できて、たとえば、ポジティブタグ、ネガティブタグ、学業タグ、SNSタグ、プログラミングタグ、などなど、

**Comment by fummicc1** [comment]
"http://d.hatena.ne.jp/keyword/%A4%CF%A4%C6%A4%CA%A5%AD%A1%BC%A5%EF%A1%BC%A5%C9%BC%AB%C6%B0%A5%EA%A5%F3%A5%AFAPI"

**Comment by fummicc1** [comment]
"https://qiita.com/yutat93/items/1b6dfe34fa8537cf3329"

**Comment by fummicc1** [comment]
https://qiita.com/hgffgh/items/f5fa228560ddc660d6bb

**Comment by fummicc1** [comment]
https://stackoverflow.com/questions/30913594/handling-xml-data-with-alamofire-in-swift/42793096

**Comment by fummicc1** [comment]
#XMLPARSERクラスを用いたサイト
https://teratail.com/questions/86617

**Comment by fummicc1** [comment]
# XMLParserを使ってXML解析
http://swift.swift-studying.com/entry/2016/01/23/131929
